---
#==============================================================================================
# Available tags:
#
#
#==============================================================================================

- import_playbook:                 ../../../snapshot.yaml

#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                              Define global settings
  hosts:                             localhost
  connection:                        local
  gather_facts:                      no

#==============================================================================================
# Set local and global variables
#==============================================================================================
  vars_files:
     - ../../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        desired_state:
          status:              present
          #status:             deleted
#==============================================================================================
# APIC access information
#==============================================================================================
    - name:                          apic details
      set_fact:
        apic_info:                   &apic_info
          host:                      "{{ apic_info.host }}"
          username:                  "{{ apic_info.username }}"
          password:                  "{{ apic_info.password }}"
          validate_certs:            no

        rest_info:                   &rest_info
          use_proxy:                 no
          path:                      /api/mo/.json
          method:                    post
  tags:                              always

#==============================================================================================
# Configure filters
#==============================================================================================
- name:                              Configure filters
  hosts:                             localhost
  connection:                        local
  gather_facts:                      no

  tasks:
    - name:                          Read variable files
      include_vars:
          name:                      filters
          dir:                       ./vars
          ignore_unknown_extensions: True
          extensions:
            - yaml

    - name:                          Create Filter
      aci_filter:
        <<:                          *apic_info
        tenant:                      "common"
        filter:                      "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        state:                       "{{ desired_state.status }}"
      with_items:
        - "{{ filters.tcp }}"
        - "{{ filters.udp }}"

# Create a new filter entry
    - name:                          Create Filter Entry
      aci_filter_entry:
        <<:                          *apic_info
        filter:                      "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        entry:                       "src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        tenant:                      "common"
        ether_type:                  "ip"
        ip_protocol:                 "{{ item.subject }}"
        dst_port:                    "{{ item.dst_port }}"
        state:                       "{{ desired_state.status }}"
# Comment in/out filters as required
      with_items:
        - "{{ filters.tcp }}"
        - "{{ filters.udp }}"
