---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        #desired_state:    present
        #desired_state:   absent
        desired_status:  modified,created
        #desired_status:  deleted

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               access-interface-policy-groups
#               vpc-interface-policy-group
#==============================================================================================
- import_playbook:        ../../snapshot.yaml
  vars:
    snapshotDescription:  Prior to configuring the Interface Policy Groups - Created by Ansible
  tags:                   snapshot

#==============================================================================================
# Create Policy Groups
#==============================================================================================
- name:                                 Configure Interface Policies
  hosts:                                localhost
  connection:                           local
  gather_facts:                         no

  vars_files:
     - ./vars/interfaces-vars.yaml

  tasks:
    - name:                             Create/Delete Access Interface Policy Group
      aci_rest:
          <<:                           *apic_info
          <<:                           *rest_info
          content:
            infraAccPortGrp:
              attributes:
                dn:                     "uni/infra/funcprof/accportgrp-{{ item.accessPolicyGroupName }}"
                name:                   "{{ item.accessPolicyGroupName }}"
                descr:                  "{{ item.descr }}"
                rn:                     "accportgrp-{{ item.accessPolicyGroupName }}"
                status:                 "{{ desired_status }}"
              children:
              - infraRsCdpIfPol:
                  attributes:
                    tnCdpIfPolName:     "{{ item.policies_interface_cdpInterface }}"
                    status:             "{{ desired_status }}"
              - infraRsAttEntP:
                  attributes:
                    tDn:                "uni/infra/attentp-{{ item.aaepName }}"
                    status:             "{{ desired_status }}"
      with_items:
        "{{ interfaces_leafInterfaces_policyGroups_leafAccessPort }}"
      loop_control:
        pause: 1
      tags:                             access-interface-policy-groups


    - name:                             Create/Delete vPC Host Interface Policy Group
      aci_rest:
          <<:                           *apic_info
          <<:                           *rest_info
          content:
            infraAccBndlGrp:
              attributes:
                descr:                  "{{ item.descr }}"
                dn:                     "uni/infra/funcprof/accbundle-{{ item.vpcPolicyGroupName }}"
                lagT:                   'node'
                name:                   "{{ item.vpcPolicyGroupName }}"
                status:                 "{{ desired_status }}"
              children:
                - infraRsCdpIfPol:
                    attributes:
                      tnCdpIfPolName:   "{{ item.policies_interface_cdpInterface }}"
                - infraRsLacpPol:
                    attributes:
                      tnLacpLagPolName: "{{ item.policies_interface_portChannel }}"
                - infraRsAttEntP:
                    attributes:
                      tDn:              "uni/infra/attentp-{{ item.aaepName }}"
      with_items:
        "{{ interfaces_leafInterfaces_policyGroups_vpcInterface }}"
      loop_control:
        pause: 1
      tags:                             vpc-interface-policy-group
