---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        #desired_state:    present
        #desired_state:   absent
        desired_status:  modified,created
        #desired_status:  deleted

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               pools
#==============================================================================================
- import_playbook:        ../../snapshot.yaml
  vars:
    snapshotDescription:  Prior to adding VLAN Pools - Created by Ansible
  tags:                   snapshot

#==============================================================================================
# Configure Pools
#==============================================================================================
- name:                        Configure Pools
  hosts:                       localhost
  connection:                  local
  gather_facts:                no

  vars_files:                  ./vars/pools-vars.yaml

  tasks:
    - name:                    Create/Delete VLAN Pool
      aci_rest:
          <<:                  *apic_info
          <<:                  *rest_info
          content:
            fvnsVlanInstP:
              attributes:
                allocMode:     "{{ item.poolType }}"
                descr:         "{{ item.descr }}"
                dn:            "uni/infra/vlanns-[{{ item.poolName }}]-[{{ item.poolType }}]"
                name:          "{{ item.poolName }}"
                status:        "{{ desired_status }}"
              children:
              - fvnsEncapBlk:
                  attributes:
                    allocMode: "{{ item.allocMode }}"
                    from:      "vlan-{{ item.start_vlanid }}"
                    role:      external
                    to:        "vlan-{{ item.end_vlanid }}"
      with_items:
        "{{ pools_vlan }}"
      loop_control:
        pause: 1        
  tags:                        pools
