---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                      Define global settings
  hosts:                     localhost
  connection:                local
  gather_facts:              no

  vars_files:
     - ./global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        #desired_state:      present
        #desired_state:      absent
        desired_status:      modified,created
        #desired_status:     deleted

    - name:                  apic details
      set_fact:
        apic_info:           &apic_info
          host:              "{{ apic_info.host }}"
          username:          "{{ apic_info.username }}"
          password:          "{{ apic_info.password }}"
          validate_certs:    no

        rest_info:           &rest_info
          use_proxy:         no
          path:              /api/mo/.json
          method:            post
  tags:                      always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               ntp
#==============================================================================================
- import_playbook:           ./snapshot.yaml
  vars:
    snapshotDescription:     Prior-to-NTP-Configuration
  tags:                      snapshot

#==============================================================================================
# Configure NTP server addresses
#==============================================================================================
- name:                         Manage NTP servers
  hosts:                        localhost
  connection:                   local
  gather_facts:                 no

  vars_files:                   ./global-vars/ntp.yaml

  tasks:
    - name:                     Create/Delete NTP server addresses
      aci_rest:
          <<:                   *apic_info
          <<:                   *rest_info
          content:
            datetimeNtpProv:
              attributes:
                annotation:     ''
                descr:          ''
                dn:             uni/fabric/time-default/ntpprov-{{item.ntpServer}}
                keyId:          '0'
                maxPoll:        '6'
                minPoll:        '4'
                name:           "{{item.ntpServer}}"
                nameAlias:      ''
                preferred:      'no'
                trueChimer:     disabled
                status:         "{{desired_status}}"
              children:
              - datetimeRsNtpProvToEpg:
                  attributes:
                    annotation: ''
                    tDn:        uni/tn-mgmt/mgmtp-default/oob-default
      with_items:
        "{{datetimeNtpProv}}"
  tags:                         ntp
