---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                                 Define global settings
  hosts:                                localhost
  connection:                           local
  gather_facts:                         no

  vars_files:
     - ./global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        #desired_state:                 present
        #desired_state:                 absent
        desired_status:                 modified,created
        #desired_status:                deleted

    - name:                             apic details
      set_fact:
        apic_info:                      &apic_info
          host:                         "{{ apic_info.host }}"
          username:                     "{{ apic_info.username }}"
          password:                     "{{ apic_info.password }}"
          validate_certs:               no

        rest_info:                      &rest_info
          use_proxy:                    no
          path:                         /api/mo/.json
          method:                       post
  tags:                                 always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               route-reflectors
#==============================================================================================
- import_playbook:                      ./snapshot.yaml
  vars:
    snapshotDescription:                Prior-to-Route-Reflector-Configuration
  tags:                                 snapshot

#==============================================================================================
# Create/Delete BGP Route Reflector Addresses
#==============================================================================================
- name:                                 Manage Route Reflector Addresses
  hosts:                                localhost
  connection:                           local
  gather_facts:                         no

  vars_files:                           ./global-vars/bgp.yaml

  tasks:
    - name:                             Create/Delete BGP Route Reflectors
      aci_rest:
          <<:                           *apic_info
          <<:                           *rest_info
          content:
            bgpInstPol:
              attributes:
                annotation:             ''
                descr:                  ''
                dn:                     uni/fabric/bgpInstP-default
                name:                   default
                nameAlias:              ''
                ownerKey:               ''
                ownerTag:               ''
              children:
                - bgpRRP:
                    attributes:
                      annotation:       ''
                      descr:            ''
                      name:             ''
                      nameAlias:        ''
                    children:
                      - bgpRRNodePEp:
                          attributes:
                            annotation: ''
                            descr:      ''
                            id:         '201'
                            nameAlias:  ''
                            podId:      '1'
                      - bgpRRNodePEp:
                          attributes:
                            annotation: ''
                            descr:      ''
                            id:         '202'
                            nameAlias:  ''
                            podId:      '1'
                - bgpExtRRP:
                    attributes:
                      annotation:       ''
                      descr:            ''
                      name:             ''
                      nameAlias:        ''
                - bgpAsP:
                    attributes:
                      annotation:       ''
                      asn:              '65000'
                      descr:            ''
                      name:             ''
                      nameAlias:        ''
#      with_items:
#        "{{bgpRRNodePEp}}"
  tags:                                 route-reflectors
