---
#==============================================================================================
# Available tags:
#
# snapshot
#
#==============================================================================================

#==============================================================================================
# Global Configuration
#==============================================================================================
- import_playbook:        ../../../snapshot.yaml
  tags:                   snapshot

- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        desired_state:
          status:         present
          #status:        deleted
          #status:        "modified,created"
          #status:        "deleted"

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#==============================================================================================
