---
#==============================================================================================
# Available tags:
#
#
#==============================================================================================


#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

#==============================================================================================
# Set local and global variables
#==============================================================================================
  vars_files:
     - ../../global-vars/apic-details.yaml

#  tasks:
#    - name:
#      set_fact:
#        desired_state:
#          status:        'modified,created'
#          status:        deleted

#==============================================================================================
# APIC access information
#==============================================================================================
  tasks:
    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Add switches to simulator
#==============================================================================================
- name:                   Manage switches in inventory
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  tasks:
    - name:               Add Leaf-101
      aci_fabric_node:
        <<:               *apic_info
        serial:           TEP-1-101
        node_id:          101
        switch:           Leaf-101
        state:            absent

    - name:               Add Leaf-102
      aci_fabric_node:
        <<:               *apic_info
        serial:           TEP-1-102
        node_id:          102
        switch:           Leaf-102
        state:            absent

    - name:               Add Spine-201
      aci_fabric_node:
        <<:               *apic_info
        serial:           TEP-1-103
        node_id:          103
        switch:           Spine-201
        state:            absent

    - name:               Add Spine-202
      aci_fabric_node:
        <<:               *apic_info
        serial:           TEP-1-104
        node_id:          202
        switch:           Spine-202
        state:            absent
