---
#==============================================================================================
# Available tags:
#
#   bridge-domains
#   gateways
#
#==============================================================================================


#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                        Define global settings
  hosts:                       localhost
  connection:                  local
  gather_facts:                no

#==============================================================================================
# Set local and global variables
#==============================================================================================
  vars_files:
     - ../../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        rest_desired_state:
          status:              'modified,created'
          #status:             deleted

        module_desired_state:  present
    #    desired_state:        absent

#==============================================================================================
# APIC access information
#==============================================================================================
    - name:                    apic details
      set_fact:
        apic_info:             &apic_info
          host:                "{{ apic_info.host }}"
          username:            "{{ apic_info.username }}"
          password:            "{{ apic_info.password }}"
          validate_certs:      no

        rest_info:             &rest_info
          use_proxy:           no
          path:                /api/mo/.json
          method:              post
  tags:                        always

#==============================================================================================
# Create Bridge Domain and Gateway
#==============================================================================================
- name:                        Create Bridge Domain
  hosts:                       localhost
  connection:                  local
  gather_facts:                no

  vars_files:
     - ./vars/bridge-domains.yaml

  tasks:
    - name:
      aci_bd:
        <<:                      *apic_info
        tenant:                  "{{ item.tenant }}"
        vrf:                     "{{ item.vrf }}"
        bd:                      "{{ item.bd }}"
        description:             "{{ item.descr }}"
        state:                   "{{ module_desired_state }}"
      with_items:
        - "{{ bd }}"
  tags:
    - bridge-domains

#==============================================================================================
# Add gateways to bridge domains
#==============================================================================================
- name:                        Add gateway to bridge domain
  hosts:                       localhost
  connection:                  local
  gather_facts:                no

  vars_files:
     - ./vars/bridge-domains.yaml

  tasks:
    - name:
      aci_bd_subnet:
        <<:                      *apic_info
        tenant:                  "{{ item.tenant }}"
        bd:                      "{{ item.bd }}"
        gateway:                 "{{ item.gw }}"
        mask:                    "{{ item.mask }}"
        state:                   "{{ module_desired_state }}"
      with_items:
        - "{{ gw }}"
  tags:
    - gateways
